import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/reset.css";
import { Header } from "@/components/Base/Header";
import { Footer } from "@/components/Base/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "suyasuyaTY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
